boat: {

    sail: {
        pressure_point_height: 2.48, # [m]  帆受力点高度（z，相对重心），将帆上的受力集中在一个点上，方便计算
        height:                 6.2, # [m]  未使用
        area:                   6.4, # [m^2]  计算帆受力用，论文2.2.1 & 2.2.2
        length:                   1, # [m]  用来算帆的摩擦阻力，在(6)和(7）的中间
        stretching:           0.961  # 文献里叫foil stretching，经过求证是展弦比，计算派生阻力时用到
    },

    rudder: {
        stretching: 2.326923076923077, # 展弦比，舵面细长，很合理
        area:                    0.13  # [m^2]
    },

    keel: {  # 船身，主要考虑水下部分，文章将船身抽象成了水中的foil
        height:      0.55, # [m]  未使用
        length:         2, # [m]  计算水的摩擦阻力用到了
        stretching: 0.605  # 计算水的派生阻力时候用到了
    },

    length:             4, # [m]  未使用
    mass:             350, # [kg]  船的质量
    height_bouyancy: 0.15, # [m]  浮心在重心以上多高，在文章(10)公式中的h_hs,0；我没太看懂那部分
    lateral_area:     2.5, # [m^2]  船侧面积，算波浪的时候用的，也是2.4  没看懂
    waterline_area:   1.6, # [m^2]  船入水后水线包围的面积，算静浮力用的，2.4节

    # cog: center of gravity
    distance_cog_sail_pressure_point:  0.43, # [m]  帆受力点离船重心水平多远(sqrt(x^2+y^2))，是在计算yaw的力矩时候用的
    distance_cog_keel_pressure_point:  0.24, # [m]  同理，船身受力点离船重心的水平距离
    distance_cog_rudder:               1.24, # [m]  同理

    distance_mast_sail_pressure_point: 0.68, # [m]  mast是挂着帆的竖着的杆子，这是帆的受力点和杆子（转轴）的水平距离
                                             # 算船yaw力矩时，虽然帆x方向受力不形成自旋，但会让帆绕着那根杆子转
                                             # 这样就会有一个反扭矩作用在船上，形成自旋。合理！


    # moi: moment of inertia
    geometrical_moi_x: 0.256,  # 绕x轴的几何转动惯量，只在计算浮力作用点偏移那里用到了，（10）里的IL
    geometrical_moi_y: 25.6,   # 同上。浮力使用几何转动惯量是因为排水是均一的，可以理解为密度均一物体的转动惯量
    moi_x: 25.6,  # 船绕轴的真正转动惯量。船不均一。
    moi_y: 1600,
    moi_z: 1066,
    

    roll_damping:      0.25,    # 这几个damping都是阻尼，我不太懂
    pitch_damping:     0.25,
    damping_z:          0.2,    # 竖直的阻尼，在计算vz变化量的时候用到
    yaw_timeconstant:     5,    # 这个不但在damping用到了，还在控制器里用到了。代码里控制器设计使用的是Riccati方法，据说是一种最优控制，不太懂
    along_damping:       15,    # 纵向阻尼，是前后水平晃，不是pitch，没有旋转，在计算vx变化量的时候用到
    transverse_damping:   5,    # 横向阻尼，是左右水平黄，不是roll，没有旋转，在计算vy变化量的时候用到
    # 阻尼我不太懂。如果是纯纯的刚体，是不是就没有阻尼了？为什么水平阻尼比旋转阻尼大了一个数量级？为什么纵向比横向大这么多？

    hull_speed:         2.5     # 船体速度，指在水里的最大速度（与船体长度相关），用来计算水的阻抗
}

environment: {  # 这个不用解释了
    water_viscosity: 0.0000001, # [Pa * s]
    air_viscosity:   0.0000171, # [Pa * s]
    water_density:        1000, # [kg/m^3]
    air_density:           1.3, # [kg/m^3]
    gravity:              9.81  # [m/s^2]
}

simulator: {  # 仿真器相关参数

    stepper: {
        # time controls
        stepsize:          0.1, # [s]  how far into the future to simulate
        clockrate:          10, # [Hz] how often to simulate
    },

    # Initial state of simulation
    initial: {
        vel_x: 0, # [m/s]
        vel_y: 0, # [m/s]
        vel_z: 0, # [m/s]

        yaw:   0,
        pitch: 0,
        roll:  0,

        roll_rate:  0,
        pitch_rate: 0,
        yaw_rate:   0,

        latitude:     18.306292, # [deg]
        longitude:   -64.951150, # [deg]

        wind_strength:   5.0,  # [m/s] 5.0 m/s ~= 4-5 bft
        wind_direction:  45.0, # [deg] wind from north-north-east

        wave_direction: 220.0,  # [deg] unused, keep for the future
        wave_length:      2.0,  # [m]   unused
        wave_amplitude:   0.0,  # [m]   unused

        sail_angle:   1,      # [rad]
        rudder_angle: 1,      # [rad]
    }
}
